version: '3.4'

services:
  db:
    image: "mariadb:10.3.16"      # use 10.3.16 to avoid this bug: https://github.com/docker-library/mariadb/issues/262
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: "magento2"
      MYSQL_PASSWORD: "magento2"
      MYSQL_ROOT_HOST: "%"
      MYSQL_INITDB_SKIP_TZINFO: 1
    expose:
      - 3306
    ports:
      - "${M2D_DB_PORT}:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - "${_M2D_DB_DIR}:/var/lib/mysql:cached"
    networks:
      - m2dnet


  web:
    build:
      args:
        TIMEZONE: "${M2D_TIMEZONE}"
    depends_on:
      - db
      - redis
    ports:
      - "${M2D_WEB_PORT}:80"
    stdin_open: true
    tty: true
    volumes:
      - ${_M2D_COMPOSER_CACHE_DIR}:/var/www/.composer:cached
      - ${_M2D_COMPOSER_AUTH_FILE}:/var/www/.composer/auth.json:cached
    networks:
      - m2dnet

  redis:
    image: "redis:5-alpine"
    expose:
      - 6379
    ports:
      - "${M2D_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - m2dnet

networks:
  m2dnet:
    driver: bridge
